api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: [ 'application/ld+json' ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
